### PR TITLE
Modifications to FASTBuild.cs for Unreal Engine 4.18 compatibility.

### PR DESCRIPTION
**Pull request by rvkennedy**
Some merges from LocalExecutor.cs, e.g. ProcessorCountMultiplier and MaxProcessorCount
Signature of ExecuteActions is modified.
BuildConfiguration no longer contains the information we need for paths, UnrealBuildTool.EngineDirectory is used.
Works with VS2017 compiler, but GetDefaultCompiler() in UEBuildWindows.cs must be modified to prioritize 2017 over 2015.
In ActionGraph.cs, add:

	else if (FASTBuild.IsAvailable())
	{
		Executor = new FASTBuild();
	}

### CODE REVIEW

**Comment by deadwizad** [comment]
I made pretty much the same changes, but mine files to link.

[(https://github.com/liamkf/Unreal_FASTBuild/issues/22)]

Have you seen this happen?

**Comment by rvkennedy** [comment]
Mine links ok, maybe post the bff file, or at least the action for ShaderCompileWorker?

**Comment by deadwizad** [comment]
Added.

[fbuild.txt](https://github.com/liamkf/Unreal_FASTBuild/files/1551791/fbuild.txt)

**Comment by yass007** [comment]
Latest now supports 4.18 and VS2017 as well as the latest FASTBuild.
If both 2015 and 2017 are present you need to modify UEBuildWindows.cs to make it choose 2017 first.
```
	// Second, default based on what's installed, test for 2015 first
	   DirectoryReference VCInstallDir;
            if (TryGetVCInstallDir(WindowsCompiler.VisualStudio2017, out VCInstallDir))
            {
                return WindowsCompiler.VisualStudio2017;
            }
            if (TryGetVCInstallDir(WindowsCompiler.VisualStudio2015, out VCInstallDir))
	    {
		return WindowsCompiler.VisualStudio2015;
	    }
```

**Pull request closed without merging**
